version: '3.8'

services:
  web:
    env_file:
      - .env
    image: node:14.5.0-alpine
    container_name: ${PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: yarn start
    ports:
      - ${PORT}:${PORT}
    tty: true
    stdin_open: true
    init: true
